gamma_product:
    resource: "@GammaProductBundle/Resources/config/routing.yml"
    prefix:   /

gamma_security:
    resource: "@GammaSecurityBundle/Resources/config/routing.yml"
    prefix:   /

gamma_main:
    resource: "@GammaMainBundle/Resources/config/routing.yml"
    prefix:   /

