security:
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false    
    
        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login: ~

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/about, roles: ROLE_ADMIN }
        - { path: ^/, roles: [ ROLE_USER, ROLE_ADMIN ]}
        

    providers:
        in_memory:
            memory:
                users:
                    tomas:  { password: tomas, roles: 'ROLE_USER' }
                    admin: { password: admin, roles: 'ROLE_ADMIN' }

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext